### ISSUE TITLE
[monitor manager] Option Menu has no attribute

### ISSUE THREAD

**Issue by fntlnz** [vivien/i3blocks-contrib#56]
There's an error in the Menu duplicating toggle

Seems that it can't find an attribute

```
$ scripts/monitor_manager 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.4/tkinter/__init__.py", line 1533, in __call__
    return self.func(*args)
  File "/usr/lib64/python3.4/tkinter/__init__.py", line 582, in callit
    func(*args)
  File "./scripts/monitor_manager", line 430, in populateGrid
    self.makeLabelRow(output, row)
  File "./scripts/monitor_manager", line 456, in makeLabelRow
    self.setMenuToDuplicate(statusOptionMenu)
  File "./scripts/monitor_manager", line 498, in setMenuToDuplicate
    output = optionMenu.output
AttributeError: 'OptionMenu' object has no attribute 'output'
```

**tkinter info**

```
>>> import tkinter
>>> tkinter.Tcl().eval('info patchlevel')
'8.6.4'
```

**Comment by kb100** [comment]
Few troubleshooting questions for you:

1. How many monitors do you have and does monitor_manager register all of them?
2. Does the error occur as soon as the block runs, or does it not happen until you click on the toggle/duplicate button?
3. Does the error always occur, or only in certain configurations of monitors?
